---
# poi
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: team5
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryznl4647.azurecr.io/tripinsights/poi:1.0
        env:
        - name: SQL_USER
          value: sqladminzNl4647
        - name: SQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: sql-password
              key: password
        - name: SQL_SERVER
          value: sqlserverznl4647.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB
        ports:
        - containerPort: 80

---
# trips
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: team5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryznl4647.azurecr.io/tripinsights/trips:1.0
        env:
        - name: SQL_USER
          value: sqladminzNl4647
        - name: SQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: sql-password
              key: password
        - name: SQL_SERVER
          value: sqlserverznl4647.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB
        - name: OPENAPI_DOCS_URI
          value: http://trips:8080
        - name: DEBUG_LOGGING
          value: "true"
        ports:
        - containerPort: 80
---
# internal trips
apiVersion: v1
kind: Service
metadata:
  namespace: team5
  name: trips
  labels:
    service: trips
spec:
  selector:
    app: trips
  ports:
  - name: service
    port: 80
    protocol: TCP
  - name: docs
    port: 8080
    protocol: TCP

---
# external trips
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: team5
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: trips


---
# tripviewer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: team5
  labels:
    app: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryznl4647.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: http://userprofile
        - name: TRIPS_API_ENDPOINT
          value: http://trips
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        ports:
        - containerPort: 80
---
# userprofile
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: team5
  labels:
    app: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryznl4647.azurecr.io/tripinsights/userprofile:1.0
        env:
        - name: SQL_USER
          value: sqladminzNl4647
        - name: SQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: sql-password
              key: password
        - name: SQL_SERVER
          value: sqlserverznl4647.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: team5
  name: userprofile
  labels:
    run: userprofile
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: userprofile


---
# user-java
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: team5
  labels:
    app: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryznl4647.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: team5
  name: user-java
  labels:
    service: user-java
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: user-java


---
# services: lb for tripviewer
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: team5
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tripviewer
