# poi
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: team5
  labels:
    app: poi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryznl4647.azurecr.io/kp/tripinsights/poi:1.0
        ports:
        - containerPort: 80
---
# trips
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: team5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryznl4647.azurecr.io/tripinsights/trips:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
# tripviewer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: team5
  labels:
    app: tripviewer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryznl4647.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: 10.244.1.27.team5.pod.cluster.local
        - name: TRIPS_API_ENDPOINT
          value: 10.244.2.26.team5.pod.cluster.local
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: "500m"
---
# userprofile
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: team5
  labels:
    app: userprofile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryznl4647.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
---
# user-java
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: team5
  labels:
    app: user-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryznl4647.azurecr.io/kp/tripinsights/user-java:1.0
        ports:
        - containerPort: 80
---
# services: lb for tripviewer
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: team5
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tripviewer