apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: poi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryznl4647.azurecr.io/kp/tripinsights/poi:1.0
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: WEB_PORT
            value: "80"
        ports:
        - containerPort: 80