apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  labels:
    app: tripviewer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
<<<<<<< HEAD
        image: registryznl4647.azurecr.io/kp/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
=======
        image: registryznl4647.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
>>>>>>> e9a0074949d0fbca2e4e45c5fcf4685caa5dd980
