apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  labels:
    app: tripviewer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: "1"